# Dependencies
highlighter:      rouge

# Permalinks
permalink: /:title/

# Setup
title : Well if you ask me...
description: my thoughts on faith, family, freedom, and fun
url:              http://www.bsoi.st
baseurl: /

author:
  name:           'Bill Soistmann'
  url:            https://twitter.com/bsoist

paginate:         20

google_analytics: UA-7456633-7
disqus: wellifyouaskme

gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-archives
  - jekyll-redirect-from

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - LICENSE.md
    - README.md
