# Dependencies
highlighter:      rouge

# Permalinks
permalink: /:title/

# Setup
title: Well if you ask me...
description: my thoughts on faith, family, freedom, and fun
url:              https://www.bsoi.st
feed_url:              https://feed.bsoi.st
baseurl: /

author:
  name:           'Bill Soistmann'
  email:          bill@soistmann.com
  url:            https://twitter.com/bsoist

paginate:         20

excerpt_separator: <!--more-->
google_analytics: UA-7456633-7
disqus: wellifyouaskme

gems:
    - jekyll-redirect-from

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - LICENSE.md
    - README.md
