# Dependencies
highlighter:      rouge

# Permalinks
permalink: /:title/

# Setup
title : Well if you ask me...
description: my thoughts on faith, family, freedom, and fun
url:              http://www.bsoi.st
baseurl: /

author:
  name:           'Bill Soistmann'
  url:            https://twitter.com/bsoist

paginate:         20

google_analytics: UA-7456633-7
disqus: wellifyouaskme

