# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title : Well if you ask me...
description: my thoughts on faith, family, freedom, and fun
url:              http://www.bsoi.st
baseurl:          /

author:
  name:           'Bill Soistmann'
  url:            https://twitter.com/bsois

paginate:         5


